### ISSUE TITLE
Emotes don't always cause chat to scroll fully

### ISSUE THREAD

**Issue by phantamanta44** [rfassoc/MysticMess#1]
...because before they fully load, their effective height is zero

**Comment by Safirah** [comment]
What do you think should be done to fix this?
Pause the scrolling until the emotes load?

**Comment by phantamanta44** [comment]
i'm thinking it probably makes sense to force the emote containers to adopt a particular aspect ratio so they consume some amount of height even if the image hasn't loaded yet
