### ISSUE TITLE
Make login button more visible

### ISSUE THREAD

**Issue by Safirah** [rfassoc/MysticMess#4]
Some users might not notice there is the possibility to login and create their own chatroom

**Comment by phantamanta44** [comment]
this is the wrong repo lol

you're looking for [this one](https://github.com/rfassoc/libseven).

**Comment by Safirah** [comment]
I'm sorry, I seem to be confusing the two repos, what is the difference between them? xD

**Comment by Safirah** [comment]
Sorry, got it now, perhaps it would be best to create a readme file, to avoid confusion? ^^
